/// An invite code used for user registration.
///
/// Invite codes are generated by admins and can be used once.
class InviteCode {
  const InviteCode({
    required this.code,
    required this.createdAt,
    this.usedByEmail,
    this.usedAt,
  });

  factory InviteCode.fromJson(Map<String, dynamic> json) {
    return InviteCode(
      code: json['code'] as String,
      createdAt: DateTime.parse(json['createdAt'] as String),
      usedByEmail: json['usedByEmail'] as String?,
      usedAt: json['usedAt'] != null
          ? DateTime.parse(json['usedAt'] as String)
          : null,
    );
  }

  final String code;
  final DateTime createdAt;
  final String? usedByEmail;
  final DateTime? usedAt;

  /// Whether this invite code has already been used.
  bool get isUsed => usedByEmail != null;
}
